name: Fetch Firebase Messages

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes (adjust as needed)
  workflow_dispatch:        # Allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # ✅ Latest version

    - name: Set up Python
      uses: actions/setup-python@v5  # ✅ Updated to v5
      with:
        python-version: 3.10

    - name: Install Python dependencies
      run: |
        pip install firebase-admin pandas tqdm  torch

    - name: Run Firebase message fetch script
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      run: |
        python fetch_firebase_messages.py

    - name: Upload CSV output
      uses: actions/upload-artifact@v4  # ✅ Updated to v4
      with:
        name: firebase-messages
        path: firebase_messages_output.csv
