name: Firebase Messages Export

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  export-messages:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install firebase-admin pandas tqdm

    - name: Run Firebase export script
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      run: python fetch_firebase_messages.py

    - name: Upload output CSV
      uses: actions/upload-artifact@v4
      with:
        name: firebase-messages
        path: firebase_messages_output.csv
