name: Update Messages Report

on:
  schedule:
    - cron: '15 */1 * * *'  # Every 1 hour and 15 minutes (at :15 past the hour)
  workflow_dispatch:

jobs:
  update-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install firebase-admin pandas tqdm openai pytz python-dotenv

    - name: Generate urgent messages report
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python fetch_firebase_messages.py

    - name: Commit and push updated master report
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git pull --rebase
        git add all_message.csv
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update: Classified messages $(date +'%Y-%m-%d %H:%M')"
        git push
