name: Dump Firebase Credentials

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # ✅ use a valid version (3.8, 3.9, 3.10, etc.)

      - name: Install dependencies
        run: |
          pip install firebase-admin pandas tqdm

      - name: Run script
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: python fetch_firebase_messages.py
