name: Fetch Firebase Messages

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes (adjust as needed)
  workflow_dispatch:        # Allow manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install firebase-admin pandas tqdm transformers torch

    - name: Run Firebase message fetch script
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      run: |
        python fetch_firebase_messages.py
